### ISSUE TITLE
How to generate code coverage

### ISSUE THREAD

**Issue by mithunbv** [estruyf/spfx-testing-wp#3]
How do we generate code coverage?
When we run the command 'gulp test', in console it says ‘writing to [dir]/temp/coverage/js’ but as such no reports get generated , the coverage folder under temp has index.html but when opened shows no data.

**Comment by estruyf** [comment]
Microsoft is currently working on providing more guidance around this topic. So at the moment, we have to wait a bit more to get the full story.

**Comment by VelinGeorgiev** [comment]
Upgrade to SPFx 1.2 packages can do the job.
See: https://github.com/SharePoint/sp-dev-fx-webparts/issues/279
