### ISSUE TITLE
Explain how you debug Unit Tests

### ISSUE THREAD

**Issue by StefanSchoof** [estruyf/spfx-testing-wp#5]
In the launch.json is a "Debug unit test (advanced)" configuration. Can you explain what to do to get it working in VSCode?

**Comment by estruyf** [comment]
@StefanSchoof you can read more about debugging SPFx unit-tests here: https://www.eliostruyf.com/how-to-debug-your-sharepoint-framework-unit-tests/

**Comment by StefanSchoof** [comment]
Thanks, I will take a look next week.
